---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui
  labels:
    component: crawler-app
    prometheus: prometheus
spec:
  selector:
    matchLabels:
      component: ui
  endpoints:
  - port: ui
