---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: crawler
  labels:
    component: crawler-app
    prometheus: prometheus
spec:
  selector:
    matchLabels:
      component: crawler
  endpoints:
  - port: crawler
    path: /
