---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ui
  labels:
    component: crawler-app
    release: prometheus
    app.kubernetes.io/component: metrics
    app.kubernetes.io/instance: stable
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: prometheus-node-exporter
    app.kubernetes.io/part-of: prometheus-node-exporter
    app.kubernetes.io/version: 1.3.1
    helm.sh/chart: prometheus-node-exporter-4.4.2
    jobLabel: node-exporter
    release: stable
spec:
  selector:
    matchLabels:
      component: ui
  endpoints:
  - port: ui
