---
service:
  internalPort: 8000
  externalPort: 8000
  replicas: 1

image:
  repository: daskain/crawler-search
  tag: 0.3

mongo:
  mongoHost: 51.250.13.202
  mongoPort: 27017

ingress:
  class: nginx

rabbit:
  rmqHost: 51.250.86.215
  rmqUser: user
  rmqPassword: pass
  rmqQueue: rabbitmq_queue
  interval: 60

config:
  excludeURL: '.*github.com'
  url: 'https://vitkhab.github.io/search_engine_test_site/'
