---
global:
  ui:
    image:
      repository: daskain/crawler-ui
      tag: latest

  crawler:
    image:
      repository: daskain/crawler-search
      tag: latest
    env:
      excludeURL: .*github.com
      url: https://vitkhab.github.io/search_engine_test_site/

  config:
    mongo:
      mongoHost: 158.160.43.138
      mongoPort: 27017
    ingress:
      class: nginx
    rabbit:
      rmqHost: 158.160.46.113
      rmqUser: user
      rmqPassword: pass
      rmqQueue: rabbitmq_queue
      interval: 60
