---
- name: Check && install python
  hosts: all
  become: true
  gather_facts: False

  tasks:
  - name: Wait 300 seconds for port 22 to become open and contain "OpenSSH"
    wait_for:
      host: '{{ ansible_host }}'
      port: 22
      delay: 10
      retry: 5

  - name: Install python for Ansible
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python)
    changed_when: False
