apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "ui.fullname" . }}-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/{{ .Release.Name }}/{{ .Chart.Name }}"
        backend:
          service:
            name: {{ template "ui.fullname" . }}
            port:
              number: {{ .Values.global.ui.service.externalPort }}