---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: crawler-app
    component: ui
    release: {{ .Release.Name }}
spec:
  type: NodePort
  ports:
  - port: {{ .Values.global.ui.service.externalPort }}
    protocol: TCP
    targetPort: {{ .Values.global.ui.service.internalPort }}
  selector:
    app: crawler-app
    component: ui
    release: {{ .Release.Name }}
