---
imagePullPolicy: IfNotPresent
gitlabUrl:  "http://62.84.117.255/"
runnerRegistrationToken: "GR13489412i4S7AZ2AGtXG5kyTmsJ"
terminationGracePeriodSeconds: 3600
concurrent: 10
checkInterval: 30
sessionServer:
 enabled: false
rbac:
  create: true
runners:
  config: |
    [[runners]]
      [runners.kubernetes]
        namespace = "{{.Release.Namespace}}"
        image = "ubuntu:20.04"
        privileged = true