---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "ui.fullname" . }}
  labels:
    app: crawler-app
    component: ui
    release: {{ .Release.Name }}
spec:
  replicas: {{ .Values.service.replicas }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: crawler-app
      component: ui
      release: {{ .Release.Name }}
  template:
    metadata:
      name: ui
      labels:
        app: crawler-app
        component: ui
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: ui
        ports:
        - containerPort: {{ .Values.service.internalPort }}
          name: ui
          protocol: TCP
        env:
        - name: MONGO
          value: {{  .Values.mongoHost | default (printf "%s-mongo" .Release.Name) }}
        - name: MONGO_PORT
          value: {{  .Values.mongoPort | default "27017" | quote }}
        - name: ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace