---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: logging
    component: kibana
spec:
  type: LoadBalancer
  ports:
  - name: kibana
    port: 80
    protocol: TCP
    targetPort: 5601
  selector:
    app: logging
    component: kibana