---
# tasks file for mongodb
- name: Install required system packages
  apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - gnupg
    - lsb-release
    - python3-pip
    - python3-setuptools
    - python3-venv