- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - "{{ GITLAB_ROOT }}/config"
    - "{{ GITLAB_ROOT }}/data"
    - "{{ GITLAB_ROOT }}/logs"

- name: Generate compose.yml
  template:
    src: compose.yml.j2
    dest: "{{ GITLAB_ROOT }}/docker-compose.yml"

- name: Create and start gitlab
  docker_compose:
    project_src: "{{ GITLAB_ROOT }}"
    build: false
  register: gitlab_web

- name: Get container IP
  set_fact:
    container_ip: "{{ gitlab_web.services.web.gitlab_web_1.networks.bridge.IPAddress }}"

- name: "wait for {{container_ip}} to come up"
  uri:
    url: "http://{{container_ip}}"
    method: GET
    status_code: 200
  register: _result
  until: _result.status == 200
  retries: 30 # retry X times  
  delay: 60 # pause for X sec b/w each call

- name: Show root password
  community.docker.docker_container_exec:
    container: gitlab_web_1
    command: grep 'Password:' /etc/gitlab/initial_root_password
  register: output


- debug:
    msg: "{{ output }}\n {{ ansible_host }}"